# Generated by Django 4.2.13 on 2026-05-07 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_status_tags_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='color',
            field=models.CharField(choices=[('green', 'green'), ('blue', 'blue'), ('teal', 'teal'), ('yellow', 'yellow'), ('brightGreen', 'brightGreen'), ('red', 'red')], default='green', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('inProgress', '진행중'), ('completed', '완료'), ('planning', '준비중')], default='inProgress', max_length=10),
        ),
    ]
