# Generated by Django 4.2.13 on 2026-05-08 05:32

import json

from django.db import migrations, models


def normalize_participants(apps, schema_editor):
    Meeting = apps.get_model("meetings", "Meeting")
    for meeting in Meeting.objects.all().only("id", "participants"):
        participants = meeting.participants
        if not participants:
            normalized = []
        elif isinstance(participants, list):
            normalized = participants
        else:
            normalized = [
                item.strip()
                for item in str(participants).split(",")
                if item.strip()
            ]
        Meeting.objects.filter(pk=meeting.pk).update(participants=json.dumps(normalized, ensure_ascii=False))


class Migration(migrations.Migration):
    dependencies = [
        ("meetings", "0002_redesign_meeting"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="action_item_checks",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="meeting",
            name="audio_file_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="meeting",
            name="source_type",
            field=models.CharField(
                choices=[("manual", "Manual"), ("upload", "Upload")],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.RunPython(normalize_participants, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="meeting",
            name="participants",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
