# Generated by Django 4.2.13 on 2026-05-07 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_update_status_and_color_choices'),
        ('schedules', '0002_remove_participants_add_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='projects.project'),
        ),
    ]
